name: todo_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.9.3
  auto_route: ^8.1.3
  flutter_animate: ^4.5.0

  cupertino_icons: ^1.0.2
  lottie: ^3.1.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  animations: ^2.0.11
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.5
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.0
  fluttertoast: ^8.2.6
  get_it: ^7.7.0
  freezed: ^2.5.2
  json_annotation: ^4.9.0
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^8.0.0
  build_runner:

  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true
flutter_intl:
  enabled: true
