// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'sign_credentials.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'sign_credentials.g.dart';

@freezed
class SignCredentials with _$SignCredentials {
  const factory SignCredentials({
    required String username,
    required String password,
  }) = _SignCredentials;

  factory SignCredentials.fromJson(Map<String, Object?> json) =>
      _$SignCredentialsFromJson(json);
}
