// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:todo_app/features/tasks/data/models/task_model.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'tasks_list_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'tasks_list_model.g.dart';

@freezed
class TasksList with _$TasksList {
  const factory TasksList({
    required List<Task> todos,
    required int total,
    required int skip,
    required int limit,
  }) = _TasksList;

  factory TasksList.fromJson(Map<String, Object?> json) =>
      _$TasksListFromJson(json);
}
